// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gowire/pkg/handler"
	"gowire/pkg/repo"
)

// Injectors from book.go:

func InitializeBookHandler() handler.BookHandler {
	bookRepo := repo.NewBookRepo()
	bookHandler := handler.NewBookHandler(bookRepo)
	return bookHandler
}

// Injectors from device.go:

func InitializeDeviceHandler() handler.BookHandler {
	bookRepo := repo.NewBookRepo()
	bookHandler := handler.NewBookHandler(bookRepo)
	return bookHandler
}

// book.go:

var bookSet = wire.NewSet(repo.NewBookRepo, wire.Bind((*repo.IBookRepo)(nil), (*repo.BookRepo)(nil)))
